### ISSUE TITLE
Single path causing crash in FF 34.0.5

### ISSUE THREAD

**Issue by lewismcarey** [ConnorAtherton/walkway#21]
I was animating a group of SVGs with walkway when I noticed that one particular SVG was causing a complete crash in FireFox (34.0.5) - I mean the browser hangs and dies with a force quit required.

I have singled it out to the following path:

<path fill="none" stroke="#F01E14" stroke-width="2" d="M382.5,57.8c0,0,3.3-39.6,41.6-29.1 c11.8,3.2,19.5,14.5,18.6,27.9c-1.3,19.3-19.5,33.8-25,38.9c-5.6,5.1-28.7,22.5-37.5,33.7c-5.8,7.4-6.8,18.1-6.8,18.1"/>

I replaced the path with another similar one and it worked fine but it just begged the question what is the issue with this one?

You can see the pen here: http://codepen.io/lewismcarey/pen/rayxbJ

**Comment by ConnorAtherton** [comment]
Hi @lewismcarey, thanks for bringing this up. Could you please paste the problematic path so I can inspect?

I'm at work right now but I will take a look when I get home.

**Comment by ConnorAtherton** [comment]
Oh dm, I guess the only path in the codepen is the one causing the problem, my bad. It works in chrome 39.0.2171.95 but I will look into the ff issue.

**Comment by lewismcarey** [comment]
Hi, yep seems to be that single path. It was a path in a larger group that made up an SVG of a number - you can probably see it in one of my other pens. 
But yes worked in Chrome and the new developer FF but not the current stable release of FF. 
I managed to pin point it to the path in the pen example.
It doesn't seem overly large or have too many anchors. 
Maybe it's a browser

**Comment by lewismcarey** [comment]
...bug or something.

**Comment by lewismcarey** [comment]
This doesnt crash in FF v35 (latest update)
Plus it didnt crash in an older FF v26 I had.

I think we can put this down to browser version anomaly ... although intrigued to find out what it was.

**Comment by ConnorAtherton** [comment]
Let me know if you run into any more troubles with this 👍
