### ISSUE TITLE
publish the latest version on bower

### ISSUE THREAD

**Issue by izzie** [ConnorAtherton/walkway#22]
current version is 0.0.4 on bower.

**Comment by ConnorAtherton** [comment]
![screen shot 2015-01-23 at 7 48 57 am](https://cloud.githubusercontent.com/assets/3777511/5877428/60ff1d20-a2d4-11e4-9ddc-0a66b246035e.png)

Running bower info returns the latest 0.0.5 version. Is it different for you?

**Comment by izzie** [comment]
bower info is same with the screenshot. But there is the different of the "getPolylineLength" function when I checkout the source by bower install

**Comment by ConnorAtherton** [comment]
Just created a new empty directory and ran bower install. Inspected the source and found the same code there. Is there a problem animating polylines for you?

**Comment by ivanthing** [comment]
Same issue for me, it's not 0.0.5 after bower install, but I set the version is 0.05 in bower.json. 
Prolblem is polyline doesn't draw on Safari

**Comment by ConnorAtherton** [comment]
Okay, thanks for the update. I'll investigate more.
