### ISSUE TITLE
Use the page visibility api to complete paths when a user navigates away

### ISSUE THREAD

**Issue by ConnorAtherton** [ConnorAtherton/walkway#24]
https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API

http://codepen.io/connoratherton/pen/ByBJxL

**Comment by ConnorAtherton** [comment]
Fixed in pr #40

**Comment by DanielRuf** [comment]
Seems the animations are directly completed when the visibility changes or am I wrong? Because it could be useful to just pause the animation and continue it.

**Comment by DanielRuf** [comment]
Not reproducible anymore in current browsers (0.0.6 without the page visibility API) http://codepen.io/anon/pen/xdjWre
