### ISSUE TITLE
How can I restart the animation ?

### ISSUE THREAD

**Issue by montalvomiguelo** [ConnorAtherton/walkway#27]
Is there any way to reinitialise the animation on click a button?

**Comment by renanCaraujo** [comment]
+1

**Comment by keeprock** [comment]
@montalvomiguelo @renanCaraujo you can try my fork: https://github.com/keeprock/walkway/blob/tab-focus-change/src/walkway.js

It has a new option redrawOnFocus (boolean). It will automatically restart animation every time tab lose focus and get it again.

**Comment by montalvomiguelo** [comment]
:+1:  thx
