### ISSUE TITLE
Add a trigger and delay options

### ISSUE THREAD

**Issue by ConnorAtherton** [ConnorAtherton/walkway#28]
Currently, all animations are scheduled to execute as soon as possible. It would be better to have more control over when an animation should start.

**Comment by wjramos** [comment]
I'm not sure if this may be beyond the scope of the library, really all you'd have to do is use your svg class as a callback for a delay or an event.

```
setTimeout( mySvg.draw, 4000 ); // draw after 4s
```

```
document.addEventListener( 'scroll', mySvg.draw ); // draw on scroll
```

**Comment by ConnorAtherton** [comment]
@wjramos That would be the simplest and easiest option to get started. 

I think my intention with this feature was to be able to add a slight animation delay for each individual element in the SVG. I think subtle offsets in the finishing times for different lines, for example, works well with this effect.

**Comment by wjramos** [comment]
Can it use `window.onload` instead of `DOMContentLoaded`? It'd let you store the object earlier and make it available sooner.

I do think that makes sense, I've seen in other animation libraries the ability to initiate lines asynchronously, or using a bezier curve like `ease-in`, ect.

**Comment by ConnorAtherton** [comment]
I don't think this change should be made to the animation library itself, but rather controlled by events added to the `draw` method you mentioned above. Closing this now, thanks for your input.
