### ISSUE TITLE
Website looks empty in Firefox 44.0.2

### ISSUE THREAD

**Issue by szynszyliszys** [ConnorAtherton/walkway#33]
The website looks as if there was nothing but the name (only thing that is not in white). After either setting body height or removing floats you can see the background color. Chrome works version works fine. Problem occurs in Firefox 44.0.2.

**Comment by ConnorAtherton** [comment]
Hey @szynszyliszys. Thanks for reporting this, I've updated the page and testing back to Firefox 43. 

Unrelated, but I was just checking out repaintless and I really like your approach. Nice job! The related blog post was an enjoyable read too. It's always a little shock to me just how much animating properties like margin and top decrease the frame rate!

**Comment by szynszyliszys** [comment]
@ConnorAtherton Thanks! Well there are always weird things about how browsers works to find out. ;) Have a nice day!

**Comment by DanielRuf** [comment]
Saw a maybe related thing which could be the cause. Using an inline SVG with a width and height value bigger than the actual viewBox, Firefox (for Android) adds a big empty space and hides some content. To me it looked like a calculation issue in Firefox. Other browsers were fine.
