### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by akhramov** [ConnorAtherton/walkway#39]
Thanks for your awesome library!

I'm wondering whether there's a release planned in the near future. I'd happy to see new features published to NPM, especially #35, which fixes annoying npm warnings during installation.

**Comment by ConnorAtherton** [comment]
@akhramov Bumped to 0.0.6 👍

**Comment by DanielRuf** [comment]
Can we have a new release for the last two commits?

**Comment by DanielRuf** [comment]
Also the new release would break / change some thins / behaviors like the new visibilitychange eventlistener ;-)
