### ISSUE TITLE
destroy / cleanup method

### ISSUE THREAD

**Issue by DanielRuf** [ConnorAtherton/walkway#45]
In SPAs (single page applications) and in other cases it probably makes sense to clear the current elements and remove the event listener.

At least it also makes sense to remove the event listener when not needed anymore (for example when the visibility was changed and all elements were drawn or in a destroy/cleanup method).

Also in my opinion it makes sense to add an option to disable the visibilitychange eventlistener or not add it and provide also an optional pause / pauseOnVisibilityHidden or similar method.

Your opinions on this?

**Comment by ConnorAtherton** [comment]
Good suggestion. I think your first two paragraphs are worthy of further treatment. I don't want to disable the visibility change listener, for reasons I have linked to in your other issue. Let me know that reasoning makes sense with you. 

Note, we do (guard against)[https://github.com/ConnorAtherton/walkway/blob/v0.0.7/src/walkway.js#L115] the case where we don't need to do any work, since the document is still in view. 

If we were going to do this, I think it would make sense for this to be a static method `Walkway.clearAll()`, or similar, since we track the elements globally to avoid setting `n` event listeners, instead of just 1.

**Comment by DanielRuf** [comment]
Just a quick additional question as npm pulled 0.0.6 (not 0.0.7): is the visibilitychange event listener removed after it was fired and `complete` called? Does not seem to be the case in the code or I oversaw something =)

A `clearAll` method to remove the instances and cleanup the stack sounds good. We could call it also manually if all objects are drawn and `redraw` and so on are not needed anymore.

**Comment by DanielRuf** [comment]
PS: the latest code is also not in https://cdn.jsdelivr.net/walkway/0.0.7/walkway.min.js

Diff between 0.0.6 and 0.0.7 https://www.diffchecker.com/MyBQtcsd

**Comment by ConnorAtherton** [comment]
> We could call it also manually if all objects are drawn..

Yeah, that sounds good 👍 

> the visibilitychange code also triggers instances which are not played 

That is for sure a bug. Perhaps we can add all these changes, update the minified bundle, and update the module correctly on npm. It looks like I just did not publish this after adding the redraw commit.

**Comment by DanielRuf** [comment]
And probably forgot `gulp`. But that is not a big deal / problem. Everyone makes mistakes sometimes and I thought I better mention that I noticed this. Better now than never I guess =)

I will test it further with the unminified version tomorrow, try to find better approaches for the visibilitychange event listener (unbind / remove after complete was called) and which elements are completed using `complete()` and `element.animationStarted` and collect the needed properties and variables which havve to be unset / cleared and event listener removed for a `clearAll` method.

11pm and just a few thoughts about possible solutions. Will present them in this issue tomorrow.

**Comment by DanielRuf** [comment]
Forgot this today, sorry. Were busy with the other projects.

Will definitely prioritize and try to do this on Monday (no job so enough time to test throughly).

**Comment by DanielRuf** [comment]
Worked on and solved a few things today / yesterday.

A first cleanup method for removing a single instance (people should still set their var to null and use the delete keyword as we have no control over these variables).

Improved rendering, initialization and code for the visibility eventlistener and also added the callback.

Improved the performance of a few lines. Will test and improve some more.

Added a few unobstrusive events like `draw(n)`, `complete` and plan some more. The event system is just an idea and would be split into another branch afterwards. So developers could use solutions like `$("svg".on("complete", function(){})` and listen to specific events.

Todo: add the global cleanAll method.

Todo: resume animation after a cancel, go to specific frame. Includes some additional calculations.

Todo: add more events.

Will present the changes this week so we can further discuss, split this into branches and PRs and merge the changes into new versions.
