### ISSUE TITLE
Renders incomplete when page is loaded in background-tab

### ISSUE THREAD

**Issue by fspoettel** [ConnorAtherton/walkway#8]
Hey Connor,
I'm playing around with walkway.js atm and there seems to be a problem when the page is loaded via a link in a new tab. (`cmd+click` link)

In Chrome/Safari, the SVG does not render at all, while in Firefox, the rendering seems to be incomplete in varying degrees.

**Screenshots of the problem:**

![Chrome/Safari](https://cloud.githubusercontent.com/assets/1682504/4897517/198d5648-6407-11e4-8213-7307e7a94aba.png)

![Firefox](https://cloud.githubusercontent.com/assets/1682504/4897518/19a2de82-6407-11e4-9e67-db3f2882c0c8.png)

**Steps to reproduce:**
1. Open walkway.js demo page in a new tab and wait for it to load completely (e.g. by cmd-clicking a link to the page)
2. Switch over to the new tab - the SVG is not rendered and rendering does not invoke

**Reproducable in:**
- Safari Version 8.0 (10600.1.25)
- Chrome 38.0.2125.111
- Firefox 34.0

**Comment by DanielRuf** [comment]
Not reproducible anymore in current browsers (0.0.6 without the page visibility API) http://codepen.io/anon/pen/xdjWre
